### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by 1800Zeta** [darrenjrobinson/PKCE#1]
I am trying to make use of this module but when I attempt to install it's reporting

`The module 'PKCE' cannot be installed or updated because the authenticode signature of the file 'PKCE.psd1' is not valid.`

**Comment by 1800Zeta** [comment]
Installed with 
`-SkipPublisherCheck `

**Comment by darrenjrobinson** [comment]
Whilst the signing certificate that was used has expired (not been revoked)
the signature is still correct.

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.3#prevent-the-signature-from-expiring

It looks like the timestamp server I used no longer exists.

Will update the version and sign with a current cert and use a
timestampserver that is current.

**Comment by darrenjrobinson** [comment]
Updated and pushed to both this Repo and the PowerShell Gallery. https://www.powershellgallery.com/packages/PKCE/1.0.2 
https://github.com/darrenjrobinson/PKCE/commit/c5b1f92f98a55d2f00b11ef553e600f04ef258d1
